---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-origin-certificate
  namespace: nginx-ingress
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: cloudflare-origin-certificate
  dnsNames:
    - 'greenpeace.org'
    - '*.greenpeace.org'
    - '*.p4.greenpeace.org'
    - '*.k8s.greenpeace.org'
  duration: 4320h
  renewBefore: 720h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-origin-issuer-prod
