apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cloudflare-origin-certificate
  namespace: nginx-ingress
spec:
  # The secret name where cert-manager should store the signed certificate
  secretName: cloudflare-origin-certificate
  dnsNames:
    - "*.greenpeace.org"
    - "*.p4.greenpeace.org"
    - "*.k8s.greenpeace.org"
    - "*.greenpeace.ch"
  # Duation of the certificate
  duration: 4320h  # 6 months
  # Renew a day before the certificate expiration
  renewBefore: 720h # 1 month
  # Reference the Origin CA Issuer you created above, which must be in the same namespace.
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: cloudflare-origin-issuer-prod