---
controller:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 95
  replicaCount: 3
  minAvailable: 2
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
  metrics:
    port: 10254
    # if this port is changed, change healthz-port: in extraArgs: accordingly
    enabled: true

    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-stack
  extraArgs:
    default-ssl-certificate: "nginx-ingress/cloudflare-origin-certificate"
  config:
    proxy-body-size: 60m
rbac:
  create: true
